"""Notification severity and delivery channel constants."""

SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_SUCCESS = "SUCCESS"

SEVERITY_CHOICES = [
    (SEVERITY_INFO, "Info"),
    (SEVERITY_WARNING, "Warning"),
    (SEVERITY_CRITICAL, "Critical"),
    (SEVERITY_SUCCESS, "Success"),
]

CHANNEL_IN_APP = "in_app"
CHANNEL_EMAIL = "email"
CHANNEL_REGULATOR_ALERT = "regulator_alert"
CHANNEL_ORGANISATION_ALERT = "organisation_alert"

NOTIFICATION_TYPE_ONBOARDING = "onboarding"
NOTIFICATION_TYPE_INVITATION = "invitation"
NOTIFICATION_TYPE_RECALL = "recall"
NOTIFICATION_TYPE_APPROVAL = "approval"
NOTIFICATION_TYPE_SUSPICIOUS_SCAN = "suspicious_scan"
NOTIFICATION_TYPE_TASK = "task"
NOTIFICATION_TYPE_REGULATOR = "regulator"
