# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
        ('products', '0002_product_dosage_guidance_product_reference_price'),
        ('serialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recall_reason', models.TextField()),
                ('effective_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='products.productbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_recalls', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Batch recall',
                'verbose_name_plural': 'Batch recalls',
                'ordering': ['-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyChainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audit_reference', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('medication_created', 'Medication created'), ('batch_created', 'Batch created'), ('manufacturer_dispatch', 'Manufacturer dispatch'), ('warehouse_receipt', 'Warehouse receipt'), ('warehouse_transfer', 'Warehouse transfer'), ('distributor_receipt', 'Distributor receipt'), ('distributor_dispatch', 'Distributor dispatch'), ('pharmacy_stocking', 'Pharmacy stocking'), ('pharmacy_sale', 'Pharmacy sale'), ('prescription_issued', 'Prescription issued'), ('patient_purchase', 'Patient purchase'), ('stock_depletion', 'Stock depletion'), ('stock_adjustment', 'Stock adjustment'), ('return', 'Return'), ('recall', 'Recall'), ('destroyed', 'Destroyed stock'), ('expired', 'Expired medication')], db_index=True, max_length=64)),
                ('quantity_delta', models.IntegerField(default=0, help_text='Signed quantity change (+ in, - out).')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspicious', 'Suspicious'), ('failed', 'Failed'), ('recalled', 'Recalled')], db_index=True, default='pending', max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_metadata', models.JSONField(blank=True, default=dict)),
                ('product_metadata', models.JSONField(blank=True, default=dict)),
                ('batch_metadata', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=16)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_immutable', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chain_transactions', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chain_transactions', to='products.productbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transactions', to='organisations.organisation')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='traceability.supplychaintransaction')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chain_transactions', to='products.product')),
                ('product_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chain_transactions', to='serialization.productserial')),
                ('source_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transactions', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Supply chain transaction',
                'verbose_name_plural': 'Supply chain transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'created_at'], name='traceabilit_transac_1efd92_idx'), models.Index(fields=['source_organisation', 'created_at'], name='traceabilit_source__54b56d_idx'), models.Index(fields=['destination_organisation', 'created_at'], name='traceabilit_destina_1d5ac7_idx'), models.Index(fields=['product', 'transaction_type'], name='traceabilit_product_f49fbb_idx'), models.Index(fields=['verification_status', 'risk_level'], name='traceabilit_verific_55ac71_idx')],
            },
        ),
    ]
