# Generated by Django 4.2.29 on 2026-05-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_batchregulatoryaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchregulatoryaudit',
            new_name='traceabilit_batch_i_1f2e0e_idx',
            old_name='traceability_batch_created_idx',
        ),
    ]
