# Generated by Django 4.2.29 on 2026-05-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traceability', '0004_phase10_custody_and_recall_execution'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serialcustodyevent',
            new_name='traceabilit_product_3a8161_idx',
            old_name='traceabilit_serial__p10_idx',
        ),
        migrations.AlterField(
            model_name='pharmacyrecallacknowledgement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmacyrecallacknowledgement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacyrecallacknowledgement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='recallexecutioncampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recallexecutioncampaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serialcustodyevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serialcustodyevent',
            name='destination_node',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('warehouse', 'Warehouse'), ('customs', 'Customs'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('patient', 'Patient')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='serialcustodyevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serialcustodyevent',
            name='source_node',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('warehouse', 'Warehouse'), ('customs', 'Customs'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital'), ('patient', 'Patient')], max_length=32),
        ),
        migrations.AlterField(
            model_name='serialcustodyevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
    ]
