# Generated by Django 4.2.29 on 2026-05-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
        ('traceability', '0005_rename_traceabilit_serial__p10_idx_traceabilit_product_3a8161_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRecallAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('escalation_required', models.BooleanField(db_index=True, default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_acks', to='traceability.recallexecutioncampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_recall_acknowledgements', to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
