# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productbatch_manufacturing_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serialization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='barcode_payload',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productserial',
            name='qr_token_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productserial',
            name='scan_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='productserial',
            name='verification_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.CreateModel(
            name='SerialSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_sequences', to='products.product')),
            ],
            options={
                'verbose_name': 'Serial sequence',
                'verbose_name_plural': 'Serial sequences',
                'unique_together': {('product', 'year')},
            },
        ),
    ]
