# Generated by Django 4.2.29 on 2026-05-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serialization', '0004_phase10_serialization_operations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serialscanrecord',
            new_name='serializati_serial__5a6348_idx',
            old_name='serializat_serial__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='serialscanrecord',
            new_name='serializati_replay__2c2bd2_idx',
            old_name='serializat_replay__d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='serialpackagingunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serialpackagingunit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serialpackagingunit',
            name='level',
            field=models.CharField(choices=[('item', 'Item'), ('inner_pack', 'Inner pack'), ('carton', 'Carton'), ('pallet', 'Pallet')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='serialpackagingunit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='serialscanrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serialscanrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serialscanrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
    ]
