# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('transport_license', models.CharField(blank=True, db_index=True, max_length=128)),
                ('fleet_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Logistics provider profile',
                'verbose_name_plural': 'Logistics provider profiles',
            },
        ),
        migrations.CreateModel(
            name='LogisticsShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tracking_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_shipments', to='organisations.organisation')),
                ('logistics_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='logistics.logisticsproviderprofile')),
                ('origin_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_shipments', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Logistics shipment',
                'verbose_name_plural': 'Logistics shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
