# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_dosage_guidance_product_reference_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsshipment',
            name='chain_integrity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='lifecycle_status',
            field=models.CharField(choices=[('created', 'Created'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('lost', 'Lost'), ('recalled', 'Recalled')], db_index=True, default='created', max_length=32),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='products.productbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.logisticsshipment')),
            ],
            options={
                'verbose_name': 'Shipment item',
                'verbose_name_plural': 'Shipment items',
            },
        ),
        migrations.CreateModel(
            name='ShipmentCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='logistics.logisticsshipment')),
            ],
            options={
                'verbose_name': 'Shipment checkpoint',
                'verbose_name_plural': 'Shipment checkpoints',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_by_name', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(db_index=True)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='logistics.logisticsshipment')),
            ],
            options={
                'verbose_name': 'Delivery confirmation',
                'verbose_name_plural': 'Delivery confirmations',
            },
        ),
        migrations.CreateModel(
            name='ColdChainLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('is_breach', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_chain_logs', to='logistics.logisticsshipment')),
            ],
            options={
                'verbose_name': 'Cold chain log',
                'verbose_name_plural': 'Cold chain logs',
                'ordering': ['recorded_at'],
            },
        ),
    ]
