# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalAlertEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('escalated_to', models.CharField(db_index=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert escalation',
                'verbose_name_plural': 'Alert escalations',
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.AddField(
            model_name='nationalalert',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalalert',
            name='evidence_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nationalalert',
            name='risk_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='nationalalert',
            index=models.Index(fields=['risk_score', 'created_at'], name='alerts_nati_risk_sc_5a2b41_idx'),
        ),
        migrations.AddField(
            model_name='nationalalertescalation',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='alerts.nationalalert'),
        ),
        migrations.AddField(
            model_name='nationalalertescalation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
