# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=128)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('payload_hash', models.CharField(db_index=True, max_length=128)),
                ('network', models.CharField(default='hyperledger-fabric', max_length=64)),
                ('anchor_status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('anchored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='blockchain__entity__c53c8d_idx'), models.Index(fields=['anchor_status', 'created_at'], name='blockchain__anchor__73cb43_idx')],
            },
        ),
    ]
