# Generated by Django 4.2.30 on 2026-05-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serialization', '0001_initial'),
        ('products', '0001_initial'),
        ('organisations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_reference', models.CharField(help_text='Secure storage path or object key for the prescription document.', max_length=512)),
                ('prescriber_name', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_uploads', to='patients.patientprofile')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_uploads', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Prescription upload',
                'verbose_name_plural': 'Prescription uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispensingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('quantity_dispensed', models.PositiveIntegerField(default=1)),
                ('dispensed_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_transactions', to='patients.patientprofile')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_transactions', to='organisations.organisation')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_transactions', to='transactions.prescriptionupload')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_transactions', to='products.product')),
                ('product_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_transactions', to='serialization.productserial')),
            ],
            options={
                'verbose_name': 'Dispensing transaction',
                'verbose_name_plural': 'Dispensing transactions',
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
