# Generated by Django 4.2.30 on 2026-05-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('verification', 'Verification'), ('inventory', 'Inventory'), ('emergency', 'Emergency'), ('fraud', 'Fraud')], db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sequence_number', models.BigIntegerField(db_index=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Verification stream event',
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('verification', 'Verification'), ('inventory', 'Inventory'), ('emergency', 'Emergency'), ('fraud', 'Fraud')], db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sequence_number', models.BigIntegerField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'System event',
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('verification', 'Verification'), ('inventory', 'Inventory'), ('emergency', 'Emergency'), ('fraud', 'Fraud')], db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sequence_number', models.BigIntegerField(db_index=True)),
                ('product_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Inventory stream event',
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('verification', 'Verification'), ('inventory', 'Inventory'), ('emergency', 'Emergency'), ('fraud', 'Fraud')], db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sequence_number', models.BigIntegerField(db_index=True)),
                ('risk_score', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Fraud stream event',
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('verification', 'Verification'), ('inventory', 'Inventory'), ('emergency', 'Emergency'), ('fraud', 'Fraud')], db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sequence_number', models.BigIntegerField(db_index=True)),
                ('epidemic_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Emergency stream event',
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
    ]
