# Generated by Django 4.2.30 on 2026-05-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('qr', 'QR code'), ('sms', 'SMS'), ('web', 'Web'), ('mobile', 'Mobile app')], db_index=True, max_length=16)),
                ('is_authentic', models.BooleanField(blank=True, null=True)),
                ('verification_message', models.CharField(blank=True, max_length=512)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product_serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_events', to='serialization.productserial')),
            ],
            options={
                'verbose_name': 'Verification event',
                'verbose_name_plural': 'Verification events',
                'ordering': ['-created_at'],
            },
        ),
    ]
