# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serialization', '0002_productserial_barcode_payload_and_more'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('serial_number', models.CharField(db_index=True, max_length=128)),
                ('outcome', models.CharField(choices=[('authentic', 'Authentic'), ('counterfeit_suspected', 'Counterfeit suspected'), ('recalled', 'Recalled'), ('expired', 'Expired'), ('duplicate_scan_detected', 'Duplicate scan detected'), ('invalid_serial', 'Invalid serial'), ('unregistered_product', 'Unregistered product')], db_index=True, max_length=32)),
                ('qr_token', models.CharField(blank=True, max_length=512)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('scan_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='serialization.productserial')),
            ],
            options={
                'verbose_name': 'Verification scan log',
                'verbose_name_plural': 'Verification scan logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_number', 'created_at'], name='verificatio_serial__cae3fe_idx'), models.Index(fields=['outcome', 'created_at'], name='verificatio_outcome_a3cea2_idx'), models.Index(fields=['device_fingerprint', 'created_at'], name='verificatio_device__0cca8a_idx')],
            },
        ),
    ]
