# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment_type', models.CharField(db_index=True, max_length=64)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('model_version', models.CharField(default='rules-v1', max_length=32)),
                ('input_features', models.JSONField(blank=True, default=dict)),
                ('output_explanation', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assessments', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment_type', 'risk_level', 'created_at'], name='ai_engine_a_assessm_15e731_idx')],
            },
        ),
    ]
