# Generated by Django 4.2.30 on 2026-05-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pharmacy_license_number', models.CharField(db_index=True, max_length=128)),
                ('superintendent_pharmacist_name', models.CharField(blank=True, max_length=255)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Structured weekly opening hours (e.g. day keys with open/close times).')),
                ('supports_delivery', models.BooleanField(default=False)),
                ('supports_emergency_supply', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Pharmacy profile',
                'verbose_name_plural': 'Pharmacy profiles',
                'ordering': ['organisation__legal_name'],
            },
        ),
    ]
