# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='is_national_registry_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Verified on NPTTE national pharmacy registry.'),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='pharmacies.pharmacyprofile'),
        ),
    ]
