# Generated by Django 4.2.29 on 2026-05-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalregulatorycertificate',
            name='certificate_type',
            field=models.CharField(choices=[('batch_approval', 'Batch approval'), ('product_certification', 'Product certification'), ('inspection_report', 'Inspection report'), ('regulator_authorization', 'Regulator authorization'), ('serialization_certificate', 'Serialization certificate')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='digitalregulatorycertificate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='digitalregulatorycertificate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='digitalregulatorycertificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
    ]
