# Generated by Django 4.2.30 on 2026-05-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('preferred_name', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('consent_to_location_search', models.BooleanField(default=False, help_text='Patient must consent before location-based pharmacy search.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient profile',
                'verbose_name_plural': 'Patient profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSearchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('search_term', models.CharField(blank=True, help_text='Free-text search input when product is resolved separately.', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_miles', models.DecimalField(decimal_places=2, default=5, help_text='Search radius from patient location in miles.', max_digits=6)),
                ('search_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('results_snapshot', models.JSONField(blank=True, default=list, help_text='Cached pharmacy matches (foundation — replaced by API responses later).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_searches', to='patients.patientprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_searches', to='products.product')),
            ],
            options={
                'verbose_name': 'Medication search request',
                'verbose_name_plural': 'Medication search requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_status', 'created_at'], name='patients_me_search__698c5a_idx')],
            },
        ),
    ]
