# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('manifest_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('origin_country', models.CharField(db_index=True, max_length=2)),
                ('port_of_entry', models.CharField(blank=True, max_length=128)),
                ('declared_at', models.DateTimeField(db_index=True)),
                ('batch_references', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_manifests', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('manifest_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('destination_country', models.CharField(db_index=True, max_length=2)),
                ('port_of_exit', models.CharField(blank=True, max_length=128)),
                ('declared_at', models.DateTimeField(db_index=True)),
                ('batch_references', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_manifests', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='BorderVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('manifest_type', models.CharField(db_index=True, max_length=16)),
                ('manifest_id', models.UUIDField(db_index=True)),
                ('border_point', models.CharField(db_index=True, max_length=128)),
                ('verification_outcome', models.CharField(db_index=True, max_length=64)),
                ('verified_at', models.DateTimeField(db_index=True)),
                ('officer_reference', models.CharField(blank=True, max_length=128)),
                ('scan_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Border verification log',
                'verbose_name_plural': 'Border verification logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
