# Generated by Django 4.2.30 on 2026-05-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Primary organisation membership for supply chain and pharmacy users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organisations.organisation'),
        ),
    ]
