# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_dosage_guidance_product_reference_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyMedicineWatchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(db_index=True, help_text='insulin, vaccine, antibiotic, narcotic, controlled, general', max_length=64)),
                ('minimum_national_stock', models.PositiveIntegerField(default=0)),
                ('is_active_watch', models.BooleanField(db_index=True, default=True)),
                ('epidemic_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_watchlist_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Emergency medicine watchlist entry',
                'verbose_name_plural': 'Emergency medicine watchlist',
                'unique_together': {('product', 'epidemic_code')},
            },
        ),
    ]
