# Generated by Django 4.2.29 on 2026-05-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0002_phase10_offline_scan_queue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offlinescanqueue',
            new_name='mobile_offl_sync_st_53fb1d_idx',
            old_name='mobile_offl_sync_p10_idx',
        ),
        migrations.AlterField(
            model_name='offlinescanqueue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlinescanqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offlinescanqueue',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
    ]
