# Generated by Django 4.2.29 on 2026-05-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0003_rename_mobile_offl_sync_p10_idx_mobile_offl_sync_st_53fb1d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileFieldEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evidence_type', models.CharField(db_index=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('case_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('sync_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileOperationalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sync_status', models.CharField(db_index=True, default='synced', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='assigned_role_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='biometric_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='device_risk_level',
            field=models.CharField(db_index=True, default='low', help_text='low|medium|high', max_length=16),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='fingerprint_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='is_emulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='is_rooted_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='os_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='platform',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='suspicious_device',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='trusted_status',
            field=models.CharField(db_index=True, default='pending', help_text='pending|trusted|suspended', max_length=16),
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['trusted_status', 'device_risk_level'], name='mobile_devi_trusted_82f49c_idx'),
        ),
        migrations.AddField(
            model_name='mobileoperationalaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobileoperationalaudit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobileoperationalaudit',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='mobile.deviceregistration'),
        ),
        migrations.AddField(
            model_name='mobileoperationalaudit',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_links', to='mobile.mobilefieldevidence'),
        ),
        migrations.AddField(
            model_name='mobilefieldevidence',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_field_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilefieldevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilefieldevidence',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_evidence', to='mobile.deviceregistration'),
        ),
        migrations.AddIndex(
            model_name='mobileoperationalaudit',
            index=models.Index(fields=['action_type', 'created_at'], name='mobile_mobi_action__e437ac_idx'),
        ),
    ]
