# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_medicationreminder_savedmedication'),
        ('organisations', '0001_initial'),
        ('products', '0002_product_dosage_guidance_product_reference_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prescription_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_fulfilled', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patientprofile')),
                ('prescriber_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_prescriptions', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='products.product')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-issued_at'],
            },
        ),
    ]
