# Generated by Django 4.2.29 on 2026-05-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanevent',
            new_name='scanning_sc_serial__02cb95_idx',
            old_name='scanning_se_serial_created_idx',
        ),
        migrations.RenameIndex(
            model_name='scanevent',
            new_name='scanning_sc_scan_ty_06ffd6_idx',
            old_name='scanning_se_type_sync_idx',
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='scan_type',
            field=models.CharField(choices=[('citizen_verify', 'Citizen verification'), ('pharmacy_receive', 'Pharmacy receive'), ('pharmacy_dispense', 'Pharmacy dispense'), ('regulator_inspection', 'Regulator inspection'), ('customs_verify', 'Customs verification'), ('warehouse_receive', 'Warehouse receive')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='synced', max_length=32),
        ),
    ]
