# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_guidance',
            field=models.TextField(blank=True, help_text='Patient-facing dosage guidance summary.'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='National reference retail price (NGN) for patient comparison.', max_digits=12, null=True),
        ),
    ]
