# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_manufacturerprofile_compliance_score_recallnotice_and_more'),
        ('products', '0002_product_dosage_guidance_product_reference_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='manufacturing_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='manufacturers.manufacturingsite'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='quantity_produced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='regulator_status',
            field=models.CharField(db_index=True, default='pending', help_text='NAFDAC/regulator approval status for batch release.', max_length=32),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='serial_range_end',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='serial_range_start',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='verification_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
