# Generated by Django 4.2 — Phase 8 traceability lifecycle

from django.db import migrations, models


def backfill_lifecycle(apps, schema_editor):
    ProductBatch = apps.get_model("products", "ProductBatch")
    for b in ProductBatch.objects.iterator():
        rs = (b.regulator_status or "").lower()
        if rs == "approved":
            b.lifecycle_status = "active" if (b.serial_range_start or "").strip() else "approved"
        elif rs == "suspended":
            b.lifecycle_status = "suspended"
        elif rs == "rejected":
            b.lifecycle_status = "draft"
        else:
            b.lifecycle_status = "draft"
        b.save(update_fields=["lifecycle_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productbatch_manufacturing_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbatch",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("recalled", "Recalled"),
                    ("expired", "Expired"),
                    ("destroyed", "Destroyed"),
                ],
                db_index=True,
                default="draft",
                help_text="Batch serialization and circulation lifecycle (Phase 8).",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_lifecycle, migrations.RunPython.noop),
    ]
