# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud_detection', '0001_initial'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudriskflag',
            name='supply_chain_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_flags', to='traceability.supplychaintransaction'),
        ),
        migrations.AddIndex(
            model_name='fraudriskflag',
            index=models.Index(fields=['flag_type', 'risk_level', 'is_resolved'], name='fraud_detec_flag_ty_0f2790_idx'),
        ),
    ]
