# Generated by Django 4.2.30 on 2026-05-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('regulator_code', models.CharField(db_index=True, max_length=32)),
                ('compliance_type', models.CharField(db_index=True, max_length=64)),
                ('is_compliant', models.BooleanField(db_index=True, default=True)),
                ('assessed_at', models.DateTimeField(db_index=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['organisation', 'regulator_code', 'is_compliant'], name='compliance__organis_e2809c_idx')],
            },
        ),
    ]
