# Generated by Django 4.2.30 on 2026-05-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_productbatch_manufacturing_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('serial_number', models.CharField(db_index=True, max_length=128)),
                ('outcome', models.CharField(db_index=True, max_length=32)),
                ('verified_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='citizen.citizenverificationsession')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicRecallNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recall_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('affected_batch_numbers', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_recalls', to='products.product')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenFraudReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('pharmacy_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('state', models.CharField(blank=True, db_index=True, max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.citizenverificationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
